version: '3'

# Define services
services:

  # App Service
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    depends_on:
      - mongo
      - redis
    environment:
      DB_NAME: admin
      DB_USERNAME: playground
      DB_PASSWORD: playground
      DB_HOST: mongo
      PASSWORD_KEY: asdjhklasdjkl
      TOKEN_KEY: jkasdjkladjkl
      SESSION_SIGNATURE_KEY: jkladjklasjklad
      REDIS_URL: redis
    networks:
      - backend

  # Postgres Service
  mongo:
    image: "mongo"
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: playground
      MONGO_INITDB_ROOT_PASSWORD: playground
    networks:
      - backend

  # Redis Service   
  redis:
    image: "redis:alpine" 
    restart: unless-stopped
    networks:
      - backend

# Networks to be created for communication between containers
networks:
  backend: